# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e4de365cf025b686d767c1bc56c0ae40d6736b391be1ed607bb8507d1c80d0928feae2495bec258cbbac3eb1ce298558df41a0a45d40537878d5ba2ea5e5575
  gmaps_api_key: ENV["GMAPS_API_KEY"]

test:
  secret_key_base: fa996c1acb4ee474beb8e0e3c8b986520cb4ec945988fb4c17e40307545fe6fd5d847f4fda357353ddb45c8d30725edddc6b5043c78bdba2d68b2aae426f09d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmaps_api_key: ENV["GMAPS_API_KEY"]
